# Generated by Codex on 2026-03-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_order_product_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_id", models.CharField(max_length=64, unique=True)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("first_name", models.CharField(blank=True, default="", max_length=150)),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                ("photo_url", models.URLField(blank=True, default="")),
                ("auth_date", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="telegram_user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="carts", to="shop.telegramuser"),
        ),
    ]
