# Generated by Codex on 2026-03-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_telegram_user_and_links"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="telegram_user_id",
            new_name="tg_user_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="username",
            new_name="tg_username",
        ),
        migrations.AddField(
            model_name="order",
            name="telegram_user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="shop.telegramuser"),
        ),
    ]
